// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: models/proto/model/model.proto at 48:1
package online.duoyu.sparkle.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Diary extends Message<Diary, Diary.Builder> {
  public static final ProtoAdapter<Diary> ADAPTER = new ProtoAdapter_Diary();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_DIARY_ID = "";

  public static final String DEFAULT_TITLE = "";

  public static final Language DEFAULT_LANGUAGE = Language.CHINESE;

  public static final String DEFAULT_CONTENT = "";

  public static final Long DEFAULT_DATE = 0L;

  public static final Integer DEFAULT_LIKES = 0;

  public static final Integer DEFAULT_COMMENTS = 0;

  public static final Integer DEFAULT_ATTENTIONS = 0;

  public static final Integer DEFAULT_CORRECTS = 0;

  public static final Long DEFAULT_DIARY_DATE = 0L;

  public static final Boolean DEFAULT_ATTENDING = false;

  public static final Boolean DEFAULT_CORRECTED = false;

  public static final Boolean DEFAULT_LIKED = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String diary_id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String title;

  @WireField(
      tag = 3,
      adapter = "online.duoyu.sparkle.model.proto.User#ADAPTER"
  )
  public final User author;

  @WireField(
      tag = 4,
      adapter = "online.duoyu.sparkle.model.proto.Language#ADAPTER"
  )
  public final Language language;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String content;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long date;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer likes;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer comments;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer attentions;

  @WireField(
      tag = 10,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer corrects;

  @WireField(
      tag = 11,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long diary_date;

  @WireField(
      tag = 12,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean attending;

  @WireField(
      tag = 13,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean corrected;

  @WireField(
      tag = 14,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean liked;

  public Diary(String diary_id, String title, User author, Language language, String content, Long date, Integer likes, Integer comments, Integer attentions, Integer corrects, Long diary_date, Boolean attending, Boolean corrected, Boolean liked) {
    this(diary_id, title, author, language, content, date, likes, comments, attentions, corrects, diary_date, attending, corrected, liked, ByteString.EMPTY);
  }

  public Diary(String diary_id, String title, User author, Language language, String content, Long date, Integer likes, Integer comments, Integer attentions, Integer corrects, Long diary_date, Boolean attending, Boolean corrected, Boolean liked, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.diary_id = diary_id;
    this.title = title;
    this.author = author;
    this.language = language;
    this.content = content;
    this.date = date;
    this.likes = likes;
    this.comments = comments;
    this.attentions = attentions;
    this.corrects = corrects;
    this.diary_date = diary_date;
    this.attending = attending;
    this.corrected = corrected;
    this.liked = liked;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.diary_id = diary_id;
    builder.title = title;
    builder.author = author;
    builder.language = language;
    builder.content = content;
    builder.date = date;
    builder.likes = likes;
    builder.comments = comments;
    builder.attentions = attentions;
    builder.corrects = corrects;
    builder.diary_date = diary_date;
    builder.attending = attending;
    builder.corrected = corrected;
    builder.liked = liked;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Diary)) return false;
    Diary o = (Diary) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(diary_id, o.diary_id)
        && Internal.equals(title, o.title)
        && Internal.equals(author, o.author)
        && Internal.equals(language, o.language)
        && Internal.equals(content, o.content)
        && Internal.equals(date, o.date)
        && Internal.equals(likes, o.likes)
        && Internal.equals(comments, o.comments)
        && Internal.equals(attentions, o.attentions)
        && Internal.equals(corrects, o.corrects)
        && Internal.equals(diary_date, o.diary_date)
        && Internal.equals(attending, o.attending)
        && Internal.equals(corrected, o.corrected)
        && Internal.equals(liked, o.liked);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (diary_id != null ? diary_id.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (author != null ? author.hashCode() : 0);
      result = result * 37 + (language != null ? language.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (date != null ? date.hashCode() : 0);
      result = result * 37 + (likes != null ? likes.hashCode() : 0);
      result = result * 37 + (comments != null ? comments.hashCode() : 0);
      result = result * 37 + (attentions != null ? attentions.hashCode() : 0);
      result = result * 37 + (corrects != null ? corrects.hashCode() : 0);
      result = result * 37 + (diary_date != null ? diary_date.hashCode() : 0);
      result = result * 37 + (attending != null ? attending.hashCode() : 0);
      result = result * 37 + (corrected != null ? corrected.hashCode() : 0);
      result = result * 37 + (liked != null ? liked.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (diary_id != null) builder.append(", diary_id=").append(diary_id);
    if (title != null) builder.append(", title=").append(title);
    if (author != null) builder.append(", author=").append(author);
    if (language != null) builder.append(", language=").append(language);
    if (content != null) builder.append(", content=").append(content);
    if (date != null) builder.append(", date=").append(date);
    if (likes != null) builder.append(", likes=").append(likes);
    if (comments != null) builder.append(", comments=").append(comments);
    if (attentions != null) builder.append(", attentions=").append(attentions);
    if (corrects != null) builder.append(", corrects=").append(corrects);
    if (diary_date != null) builder.append(", diary_date=").append(diary_date);
    if (attending != null) builder.append(", attending=").append(attending);
    if (corrected != null) builder.append(", corrected=").append(corrected);
    if (liked != null) builder.append(", liked=").append(liked);
    return builder.replace(0, 2, "Diary{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Diary, Builder> {
    public String diary_id;

    public String title;

    public User author;

    public Language language;

    public String content;

    public Long date;

    public Integer likes;

    public Integer comments;

    public Integer attentions;

    public Integer corrects;

    public Long diary_date;

    public Boolean attending;

    public Boolean corrected;

    public Boolean liked;

    public Builder() {
    }

    public Builder diary_id(String diary_id) {
      this.diary_id = diary_id;
      return this;
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder author(User author) {
      this.author = author;
      return this;
    }

    public Builder language(Language language) {
      this.language = language;
      return this;
    }

    public Builder content(String content) {
      this.content = content;
      return this;
    }

    public Builder date(Long date) {
      this.date = date;
      return this;
    }

    public Builder likes(Integer likes) {
      this.likes = likes;
      return this;
    }

    public Builder comments(Integer comments) {
      this.comments = comments;
      return this;
    }

    public Builder attentions(Integer attentions) {
      this.attentions = attentions;
      return this;
    }

    public Builder corrects(Integer corrects) {
      this.corrects = corrects;
      return this;
    }

    public Builder diary_date(Long diary_date) {
      this.diary_date = diary_date;
      return this;
    }

    public Builder attending(Boolean attending) {
      this.attending = attending;
      return this;
    }

    public Builder corrected(Boolean corrected) {
      this.corrected = corrected;
      return this;
    }

    public Builder liked(Boolean liked) {
      this.liked = liked;
      return this;
    }

    @Override
    public Diary build() {
      return new Diary(diary_id, title, author, language, content, date, likes, comments, attentions, corrects, diary_date, attending, corrected, liked, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Diary extends ProtoAdapter<Diary> {
    ProtoAdapter_Diary() {
      super(FieldEncoding.LENGTH_DELIMITED, Diary.class);
    }

    @Override
    public int encodedSize(Diary value) {
      return (value.diary_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.diary_id) : 0)
          + (value.title != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.title) : 0)
          + (value.author != null ? User.ADAPTER.encodedSizeWithTag(3, value.author) : 0)
          + (value.language != null ? Language.ADAPTER.encodedSizeWithTag(4, value.language) : 0)
          + (value.content != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.content) : 0)
          + (value.date != null ? ProtoAdapter.INT64.encodedSizeWithTag(6, value.date) : 0)
          + (value.likes != null ? ProtoAdapter.INT32.encodedSizeWithTag(7, value.likes) : 0)
          + (value.comments != null ? ProtoAdapter.INT32.encodedSizeWithTag(8, value.comments) : 0)
          + (value.attentions != null ? ProtoAdapter.INT32.encodedSizeWithTag(9, value.attentions) : 0)
          + (value.corrects != null ? ProtoAdapter.INT32.encodedSizeWithTag(10, value.corrects) : 0)
          + (value.diary_date != null ? ProtoAdapter.INT64.encodedSizeWithTag(11, value.diary_date) : 0)
          + (value.attending != null ? ProtoAdapter.BOOL.encodedSizeWithTag(12, value.attending) : 0)
          + (value.corrected != null ? ProtoAdapter.BOOL.encodedSizeWithTag(13, value.corrected) : 0)
          + (value.liked != null ? ProtoAdapter.BOOL.encodedSizeWithTag(14, value.liked) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Diary value) throws IOException {
      if (value.diary_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.diary_id);
      if (value.title != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.title);
      if (value.author != null) User.ADAPTER.encodeWithTag(writer, 3, value.author);
      if (value.language != null) Language.ADAPTER.encodeWithTag(writer, 4, value.language);
      if (value.content != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.content);
      if (value.date != null) ProtoAdapter.INT64.encodeWithTag(writer, 6, value.date);
      if (value.likes != null) ProtoAdapter.INT32.encodeWithTag(writer, 7, value.likes);
      if (value.comments != null) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.comments);
      if (value.attentions != null) ProtoAdapter.INT32.encodeWithTag(writer, 9, value.attentions);
      if (value.corrects != null) ProtoAdapter.INT32.encodeWithTag(writer, 10, value.corrects);
      if (value.diary_date != null) ProtoAdapter.INT64.encodeWithTag(writer, 11, value.diary_date);
      if (value.attending != null) ProtoAdapter.BOOL.encodeWithTag(writer, 12, value.attending);
      if (value.corrected != null) ProtoAdapter.BOOL.encodeWithTag(writer, 13, value.corrected);
      if (value.liked != null) ProtoAdapter.BOOL.encodeWithTag(writer, 14, value.liked);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Diary decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.diary_id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.title(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.author(User.ADAPTER.decode(reader)); break;
          case 4: {
            try {
              builder.language(Language.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 5: builder.content(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.date(ProtoAdapter.INT64.decode(reader)); break;
          case 7: builder.likes(ProtoAdapter.INT32.decode(reader)); break;
          case 8: builder.comments(ProtoAdapter.INT32.decode(reader)); break;
          case 9: builder.attentions(ProtoAdapter.INT32.decode(reader)); break;
          case 10: builder.corrects(ProtoAdapter.INT32.decode(reader)); break;
          case 11: builder.diary_date(ProtoAdapter.INT64.decode(reader)); break;
          case 12: builder.attending(ProtoAdapter.BOOL.decode(reader)); break;
          case 13: builder.corrected(ProtoAdapter.BOOL.decode(reader)); break;
          case 14: builder.liked(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Diary redact(Diary value) {
      Builder builder = value.newBuilder();
      if (builder.author != null) builder.author = User.ADAPTER.redact(builder.author);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
