// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: models/proto/business/user.proto at 100:1
package online.duoyu.sparkle.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;

import java.io.IOException;
import java.util.List;

import okio.ByteString;

public final class TimelineResponse extends Message<TimelineResponse, TimelineResponse.Builder> {
  public static final ProtoAdapter<TimelineResponse> ADAPTER = new ProtoAdapter_TimelineResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "online.duoyu.sparkle.model.proto.Happening#ADAPTER",
      label = WireField.Label.REPEATED)
  public final List<Happening> happenings;

  @WireField(
      tag = 2,
      adapter = "online.duoyu.sparkle.model.proto.Cursor#ADAPTER")
  public final Cursor cursor;

  public TimelineResponse(List<Happening> happenings, Cursor cursor) {
    this(happenings, cursor, ByteString.EMPTY);
  }

  public TimelineResponse(List<Happening> happenings, Cursor cursor, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.happenings = Internal.immutableCopyOf("happenings", happenings);
    this.cursor = cursor;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.happenings = Internal.copyOf("happenings", happenings);
    builder.cursor = cursor;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TimelineResponse)) return false;
    TimelineResponse o = (TimelineResponse) other;
    return unknownFields().equals(o.unknownFields()) && happenings.equals(o.happenings) && Internal.equals(cursor, o.cursor);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + happenings.hashCode();
      result = result * 37 + (cursor != null ? cursor.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!happenings.isEmpty()) builder.append(", happenings=").append(happenings);
    if (cursor != null) builder.append(", cursor=").append(cursor);
    return builder.replace(0, 2, "TimelineResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TimelineResponse, Builder> {
    public List<Happening> happenings;

    public Cursor cursor;

    public Builder() {
      happenings = Internal.newMutableList();
    }

    public Builder happenings(List<Happening> happenings) {
      Internal.checkElementsNotNull(happenings);
      this.happenings = happenings;
      return this;
    }

    public Builder cursor(Cursor cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public TimelineResponse build() {
      return new TimelineResponse(happenings, cursor, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TimelineResponse extends ProtoAdapter<TimelineResponse> {
    ProtoAdapter_TimelineResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, TimelineResponse.class);
    }

    @Override
    public int encodedSize(TimelineResponse value) {
      return Happening.ADAPTER.asRepeated().encodedSizeWithTag(1, value.happenings) + (value.cursor != null ? Cursor.ADAPTER.encodedSizeWithTag(2, value.cursor) : 0) + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, TimelineResponse value) throws IOException {
      Happening.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.happenings);
      if (value.cursor != null) Cursor.ADAPTER.encodeWithTag(writer, 2, value.cursor);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TimelineResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1; ) {
        switch (tag) {
          case 1:
            builder.happenings.add(Happening.ADAPTER.decode(reader));
            break;
          case 2:
            builder.cursor(Cursor.ADAPTER.decode(reader));
            break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public TimelineResponse redact(TimelineResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.happenings, Happening.ADAPTER);
      if (builder.cursor != null) builder.cursor = Cursor.ADAPTER.redact(builder.cursor);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
