// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: models/proto/business/notify.proto at 34:1
package online.duoyu.sparkle.model.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireEnum;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;

import java.io.IOException;

import okio.ByteString;

public final class UnreadNotificationResponse extends Message<UnreadNotificationResponse, UnreadNotificationResponse.Builder> {
  public static final ProtoAdapter<UnreadNotificationResponse> ADAPTER = new ProtoAdapter_UnreadNotificationResponse();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_SUCCESS = false;

  public static final Integer DEFAULT_UNREAD_NUM = 0;

  public static final Errno DEFAULT_ERRNO = Errno.UNKNOWN;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL")
  public final Boolean success;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32")
  public final Integer unread_num;

  @WireField(
      tag = 3,
      adapter = "online.duoyu.sparkle.model.proto.UnreadNotificationResponse$Errno#ADAPTER")
  public final Errno errno;

  public UnreadNotificationResponse(Boolean success, Integer unread_num, Errno errno) {
    this(success, unread_num, errno, ByteString.EMPTY);
  }

  public UnreadNotificationResponse(Boolean success, Integer unread_num, Errno errno, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.success = success;
    this.unread_num = unread_num;
    this.errno = errno;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.success = success;
    builder.unread_num = unread_num;
    builder.errno = errno;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UnreadNotificationResponse)) return false;
    UnreadNotificationResponse o = (UnreadNotificationResponse) other;
    return unknownFields().equals(o.unknownFields()) && Internal.equals(success, o.success) && Internal.equals(unread_num, o.unread_num) && Internal.equals(errno, o.errno);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (success != null ? success.hashCode() : 0);
      result = result * 37 + (unread_num != null ? unread_num.hashCode() : 0);
      result = result * 37 + (errno != null ? errno.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (success != null) builder.append(", success=").append(success);
    if (unread_num != null) builder.append(", unread_num=").append(unread_num);
    if (errno != null) builder.append(", errno=").append(errno);
    return builder.replace(0, 2, "UnreadNotificationResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UnreadNotificationResponse, Builder> {
    public Boolean success;

    public Integer unread_num;

    public Errno errno;

    public Builder() {
    }

    public Builder success(Boolean success) {
      this.success = success;
      return this;
    }

    public Builder unread_num(Integer unread_num) {
      this.unread_num = unread_num;
      return this;
    }

    public Builder errno(Errno errno) {
      this.errno = errno;
      return this;
    }

    @Override
    public UnreadNotificationResponse build() {
      return new UnreadNotificationResponse(success, unread_num, errno, super.buildUnknownFields());
    }
  }

  public enum Errno implements WireEnum {
    UNKNOWN(0);

    public static final ProtoAdapter<Errno> ADAPTER = ProtoAdapter.newEnumAdapter(Errno.class);

    private final int value;

    Errno(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static Errno fromValue(int value) {
      switch (value) {
        case 0:
          return UNKNOWN;
        default:
          return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }
  }

  private static final class ProtoAdapter_UnreadNotificationResponse extends ProtoAdapter<UnreadNotificationResponse> {
    ProtoAdapter_UnreadNotificationResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, UnreadNotificationResponse.class);
    }

    @Override
    public int encodedSize(UnreadNotificationResponse value) {
      return (value.success != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.success) : 0) + (value.unread_num != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.unread_num) : 0) + (value.errno != null ? Errno.ADAPTER.encodedSizeWithTag(3, value.errno) : 0) + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UnreadNotificationResponse value) throws IOException {
      if (value.success != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.success);
      if (value.unread_num != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.unread_num);
      if (value.errno != null) Errno.ADAPTER.encodeWithTag(writer, 3, value.errno);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UnreadNotificationResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1; ) {
        switch (tag) {
          case 1:
            builder.success(ProtoAdapter.BOOL.decode(reader));
            break;
          case 2:
            builder.unread_num(ProtoAdapter.INT32.decode(reader));
            break;
          case 3: {
            try {
              builder.errno(Errno.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UnreadNotificationResponse redact(UnreadNotificationResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
