// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: models/proto/business/notify.proto at 14:1
package online.duoyu.sparkle.model.business;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;
import online.duoyu.sparkle.model.proto.Cursor;
import online.duoyu.sparkle.model.proto.Notification;

public final class CurrentUserNotificationResponse extends Message<CurrentUserNotificationResponse, CurrentUserNotificationResponse.Builder> {
  public static final ProtoAdapter<CurrentUserNotificationResponse> ADAPTER = new ProtoAdapter_CurrentUserNotificationResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "online.duoyu.sparkle.model.proto.Notification#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Notification> notifications;

  @WireField(
      tag = 2,
      adapter = "online.duoyu.sparkle.model.proto.Cursor#ADAPTER"
  )
  public final Cursor cursor;

  public CurrentUserNotificationResponse(List<Notification> notifications, Cursor cursor) {
    this(notifications, cursor, ByteString.EMPTY);
  }

  public CurrentUserNotificationResponse(List<Notification> notifications, Cursor cursor, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.notifications = Internal.immutableCopyOf("notifications", notifications);
    this.cursor = cursor;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.notifications = Internal.copyOf("notifications", notifications);
    builder.cursor = cursor;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CurrentUserNotificationResponse)) return false;
    CurrentUserNotificationResponse o = (CurrentUserNotificationResponse) other;
    return unknownFields().equals(o.unknownFields())
        && notifications.equals(o.notifications)
        && Internal.equals(cursor, o.cursor);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + notifications.hashCode();
      result = result * 37 + (cursor != null ? cursor.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!notifications.isEmpty()) builder.append(", notifications=").append(notifications);
    if (cursor != null) builder.append(", cursor=").append(cursor);
    return builder.replace(0, 2, "CurrentUserNotificationResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CurrentUserNotificationResponse, Builder> {
    public List<Notification> notifications;

    public Cursor cursor;

    public Builder() {
      notifications = Internal.newMutableList();
    }

    public Builder notifications(List<Notification> notifications) {
      Internal.checkElementsNotNull(notifications);
      this.notifications = notifications;
      return this;
    }

    public Builder cursor(Cursor cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public CurrentUserNotificationResponse build() {
      return new CurrentUserNotificationResponse(notifications, cursor, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CurrentUserNotificationResponse extends ProtoAdapter<CurrentUserNotificationResponse> {
    ProtoAdapter_CurrentUserNotificationResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, CurrentUserNotificationResponse.class);
    }

    @Override
    public int encodedSize(CurrentUserNotificationResponse value) {
      return Notification.ADAPTER.asRepeated().encodedSizeWithTag(1, value.notifications)
          + (value.cursor != null ? Cursor.ADAPTER.encodedSizeWithTag(2, value.cursor) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CurrentUserNotificationResponse value) throws IOException {
      Notification.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.notifications);
      if (value.cursor != null) Cursor.ADAPTER.encodeWithTag(writer, 2, value.cursor);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CurrentUserNotificationResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.notifications.add(Notification.ADAPTER.decode(reader)); break;
          case 2: builder.cursor(Cursor.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CurrentUserNotificationResponse redact(CurrentUserNotificationResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.notifications, Notification.ADAPTER);
      if (builder.cursor != null) builder.cursor = Cursor.ADAPTER.redact(builder.cursor);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
