// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: models/proto/business/comment.proto at 10:1
package online.duoyu.sparkle.model.business;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;
import online.duoyu.sparkle.model.proto.Cursor;

public final class GetCommentsByDiaryIdRequest extends Message<GetCommentsByDiaryIdRequest, GetCommentsByDiaryIdRequest.Builder> {
  public static final ProtoAdapter<GetCommentsByDiaryIdRequest> ADAPTER = new ProtoAdapter_GetCommentsByDiaryIdRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_DIARY_ID = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String diary_id;

  @WireField(
      tag = 2,
      adapter = "online.duoyu.sparkle.model.proto.Cursor#ADAPTER"
  )
  public final Cursor cursor;

  public GetCommentsByDiaryIdRequest(String diary_id, Cursor cursor) {
    this(diary_id, cursor, ByteString.EMPTY);
  }

  public GetCommentsByDiaryIdRequest(String diary_id, Cursor cursor, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.diary_id = diary_id;
    this.cursor = cursor;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.diary_id = diary_id;
    builder.cursor = cursor;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetCommentsByDiaryIdRequest)) return false;
    GetCommentsByDiaryIdRequest o = (GetCommentsByDiaryIdRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(diary_id, o.diary_id)
        && Internal.equals(cursor, o.cursor);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (diary_id != null ? diary_id.hashCode() : 0);
      result = result * 37 + (cursor != null ? cursor.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (diary_id != null) builder.append(", diary_id=").append(diary_id);
    if (cursor != null) builder.append(", cursor=").append(cursor);
    return builder.replace(0, 2, "GetCommentsByDiaryIdRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetCommentsByDiaryIdRequest, Builder> {
    public String diary_id;

    public Cursor cursor;

    public Builder() {
    }

    public Builder diary_id(String diary_id) {
      this.diary_id = diary_id;
      return this;
    }

    public Builder cursor(Cursor cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public GetCommentsByDiaryIdRequest build() {
      return new GetCommentsByDiaryIdRequest(diary_id, cursor, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetCommentsByDiaryIdRequest extends ProtoAdapter<GetCommentsByDiaryIdRequest> {
    ProtoAdapter_GetCommentsByDiaryIdRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, GetCommentsByDiaryIdRequest.class);
    }

    @Override
    public int encodedSize(GetCommentsByDiaryIdRequest value) {
      return (value.diary_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.diary_id) : 0)
          + (value.cursor != null ? Cursor.ADAPTER.encodedSizeWithTag(2, value.cursor) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetCommentsByDiaryIdRequest value) throws IOException {
      if (value.diary_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.diary_id);
      if (value.cursor != null) Cursor.ADAPTER.encodeWithTag(writer, 2, value.cursor);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetCommentsByDiaryIdRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.diary_id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.cursor(Cursor.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetCommentsByDiaryIdRequest redact(GetCommentsByDiaryIdRequest value) {
      Builder builder = value.newBuilder();
      if (builder.cursor != null) builder.cursor = Cursor.ADAPTER.redact(builder.cursor);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
