// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: models/proto/business/account.proto at 31:1
package online.duoyu.sparkle.model.business;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;
import online.duoyu.sparkle.model.proto.Language;
import online.duoyu.sparkle.model.proto.PrehashedPassword;

public final class RegisterRequest extends Message<RegisterRequest, RegisterRequest.Builder> {
  public static final ProtoAdapter<RegisterRequest> ADAPTER = new ProtoAdapter_RegisterRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_EMAIL = "";

  public static final String DEFAULT_EMAIL_VERIFICATION_CODE = "";

  public static final String DEFAULT_NICKNAME = "";

  public static final String DEFAULT_AVATAR = "";

  public static final String DEFAULT_REGION = "";

  public static final String DEFAULT_INTRODUCE = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String email;

  @WireField(
      tag = 2,
      adapter = "online.duoyu.sparkle.model.proto.PrehashedPassword#ADAPTER"
  )
  public final PrehashedPassword password;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String email_verification_code;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String nickname;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String avatar;

  @WireField(
      tag = 6,
      adapter = "online.duoyu.sparkle.model.proto.Language#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Language> native_languages;

  @WireField(
      tag = 7,
      adapter = "online.duoyu.sparkle.model.proto.Language#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Language> target_languages;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String region;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String introduce;

  public RegisterRequest(String email, PrehashedPassword password, String email_verification_code, String nickname, String avatar, List<Language> native_languages, List<Language> target_languages, String region, String introduce) {
    this(email, password, email_verification_code, nickname, avatar, native_languages, target_languages, region, introduce, ByteString.EMPTY);
  }

  public RegisterRequest(String email, PrehashedPassword password, String email_verification_code, String nickname, String avatar, List<Language> native_languages, List<Language> target_languages, String region, String introduce, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.email = email;
    this.password = password;
    this.email_verification_code = email_verification_code;
    this.nickname = nickname;
    this.avatar = avatar;
    this.native_languages = Internal.immutableCopyOf("native_languages", native_languages);
    this.target_languages = Internal.immutableCopyOf("target_languages", target_languages);
    this.region = region;
    this.introduce = introduce;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.email = email;
    builder.password = password;
    builder.email_verification_code = email_verification_code;
    builder.nickname = nickname;
    builder.avatar = avatar;
    builder.native_languages = Internal.copyOf("native_languages", native_languages);
    builder.target_languages = Internal.copyOf("target_languages", target_languages);
    builder.region = region;
    builder.introduce = introduce;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RegisterRequest)) return false;
    RegisterRequest o = (RegisterRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(email, o.email)
        && Internal.equals(password, o.password)
        && Internal.equals(email_verification_code, o.email_verification_code)
        && Internal.equals(nickname, o.nickname)
        && Internal.equals(avatar, o.avatar)
        && native_languages.equals(o.native_languages)
        && target_languages.equals(o.target_languages)
        && Internal.equals(region, o.region)
        && Internal.equals(introduce, o.introduce);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (email != null ? email.hashCode() : 0);
      result = result * 37 + (password != null ? password.hashCode() : 0);
      result = result * 37 + (email_verification_code != null ? email_verification_code.hashCode() : 0);
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (avatar != null ? avatar.hashCode() : 0);
      result = result * 37 + native_languages.hashCode();
      result = result * 37 + target_languages.hashCode();
      result = result * 37 + (region != null ? region.hashCode() : 0);
      result = result * 37 + (introduce != null ? introduce.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (email != null) builder.append(", email=").append(email);
    if (password != null) builder.append(", password=").append(password);
    if (email_verification_code != null) builder.append(", email_verification_code=").append(email_verification_code);
    if (nickname != null) builder.append(", nickname=").append(nickname);
    if (avatar != null) builder.append(", avatar=").append(avatar);
    if (!native_languages.isEmpty()) builder.append(", native_languages=").append(native_languages);
    if (!target_languages.isEmpty()) builder.append(", target_languages=").append(target_languages);
    if (region != null) builder.append(", region=").append(region);
    if (introduce != null) builder.append(", introduce=").append(introduce);
    return builder.replace(0, 2, "RegisterRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RegisterRequest, Builder> {
    public String email;

    public PrehashedPassword password;

    public String email_verification_code;

    public String nickname;

    public String avatar;

    public List<Language> native_languages;

    public List<Language> target_languages;

    public String region;

    public String introduce;

    public Builder() {
      native_languages = Internal.newMutableList();
      target_languages = Internal.newMutableList();
    }

    public Builder email(String email) {
      this.email = email;
      return this;
    }

    public Builder password(PrehashedPassword password) {
      this.password = password;
      return this;
    }

    public Builder email_verification_code(String email_verification_code) {
      this.email_verification_code = email_verification_code;
      return this;
    }

    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    public Builder avatar(String avatar) {
      this.avatar = avatar;
      return this;
    }

    public Builder native_languages(List<Language> native_languages) {
      Internal.checkElementsNotNull(native_languages);
      this.native_languages = native_languages;
      return this;
    }

    public Builder target_languages(List<Language> target_languages) {
      Internal.checkElementsNotNull(target_languages);
      this.target_languages = target_languages;
      return this;
    }

    public Builder region(String region) {
      this.region = region;
      return this;
    }

    public Builder introduce(String introduce) {
      this.introduce = introduce;
      return this;
    }

    @Override
    public RegisterRequest build() {
      return new RegisterRequest(email, password, email_verification_code, nickname, avatar, native_languages, target_languages, region, introduce, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RegisterRequest extends ProtoAdapter<RegisterRequest> {
    ProtoAdapter_RegisterRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, RegisterRequest.class);
    }

    @Override
    public int encodedSize(RegisterRequest value) {
      return (value.email != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.email) : 0)
          + (value.password != null ? PrehashedPassword.ADAPTER.encodedSizeWithTag(2, value.password) : 0)
          + (value.email_verification_code != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.email_verification_code) : 0)
          + (value.nickname != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.nickname) : 0)
          + (value.avatar != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.avatar) : 0)
          + Language.ADAPTER.asRepeated().encodedSizeWithTag(6, value.native_languages)
          + Language.ADAPTER.asRepeated().encodedSizeWithTag(7, value.target_languages)
          + (value.region != null ? ProtoAdapter.STRING.encodedSizeWithTag(8, value.region) : 0)
          + (value.introduce != null ? ProtoAdapter.STRING.encodedSizeWithTag(9, value.introduce) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, RegisterRequest value) throws IOException {
      if (value.email != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.email);
      if (value.password != null) PrehashedPassword.ADAPTER.encodeWithTag(writer, 2, value.password);
      if (value.email_verification_code != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.email_verification_code);
      if (value.nickname != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.nickname);
      if (value.avatar != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.avatar);
      Language.ADAPTER.asRepeated().encodeWithTag(writer, 6, value.native_languages);
      Language.ADAPTER.asRepeated().encodeWithTag(writer, 7, value.target_languages);
      if (value.region != null) ProtoAdapter.STRING.encodeWithTag(writer, 8, value.region);
      if (value.introduce != null) ProtoAdapter.STRING.encodeWithTag(writer, 9, value.introduce);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RegisterRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.email(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.password(PrehashedPassword.ADAPTER.decode(reader)); break;
          case 3: builder.email_verification_code(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.nickname(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.avatar(ProtoAdapter.STRING.decode(reader)); break;
          case 6: {
            try {
              builder.native_languages.add(Language.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 7: {
            try {
              builder.target_languages.add(Language.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 8: builder.region(ProtoAdapter.STRING.decode(reader)); break;
          case 9: builder.introduce(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public RegisterRequest redact(RegisterRequest value) {
      Builder builder = value.newBuilder();
      if (builder.password != null) builder.password = PrehashedPassword.ADAPTER.redact(builder.password);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
