// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: models/proto/business/notify.proto at 31:1
package online.duoyu.sparkle.model.business;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UnreadNotificationRequest extends Message<UnreadNotificationRequest, UnreadNotificationRequest.Builder> {
  public static final ProtoAdapter<UnreadNotificationRequest> ADAPTER = new ProtoAdapter_UnreadNotificationRequest();

  private static final long serialVersionUID = 0L;

  public UnreadNotificationRequest() {
    this(ByteString.EMPTY);
  }

  public UnreadNotificationRequest(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof UnreadNotificationRequest;
  }

  @Override
  public int hashCode() {
    return unknownFields().hashCode();
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "UnreadNotificationRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UnreadNotificationRequest, Builder> {
    public Builder() {
    }

    @Override
    public UnreadNotificationRequest build() {
      return new UnreadNotificationRequest(super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UnreadNotificationRequest extends ProtoAdapter<UnreadNotificationRequest> {
    ProtoAdapter_UnreadNotificationRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, UnreadNotificationRequest.class);
    }

    @Override
    public int encodedSize(UnreadNotificationRequest value) {
      return value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UnreadNotificationRequest value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UnreadNotificationRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UnreadNotificationRequest redact(UnreadNotificationRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
