package online.duoyu.sparkle.network;

/**
 * Created by littlekey on 12/19/16.
 */

public enum ApiType {
  FOLLOW_USER_DIARY, CURRENT_USER, LOGIN, RECENT_DIARY, GET_CORRECT_BY_DIARY_AND_USER,
  GET_CORRECTS_BY_DIARY, CORRECT, ATTENTION_DIARY, UNATTENDED_DIARY, DIARY, GET_DIARY_BY_ID
}
