package online.duoyu.sparkle.network;

/**
 * Created by littlekey on 12/19/16.
 */

public enum ApiType {
  FOLLOW_USER_DIARY, CURRENT_USER, LOGIN, RECENT_DIARY, GET_CORRECT_BY_DIARY_AND_USER,
  GET_CORRECTS_SENTENCE_BY_DIARY, CORRECT, ATTENTION_DIARY, UNATTENDED_DIARY, DIARY, GET_DIARY_BY_ID,
  LIKE_DIARY, LIKE_CORRECT, LIKE_COMMENT, UNLIKE_DIARY, UNLIKE_CORRECT, UNLIKE_COMMENT,
  GET_CORRECTS_BY_DIARY, GET_COMMENTS_BY_DIARY, COMMENT, ATTENTION_NOTIFICATION, LIKED_NOTIFICATION
}
